In [1]:
#question1


In [7]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([5.5,6.5,7.5,8.5])
#addition
print(x+y)
#subtraction
print(x-y)
#multiplication
print(x*y)
#division
print(x/y)

[ 6.5  8.5 10.5 12.5]
[-4.5 -4.5 -4.5 -4.5]
[ 5.5 13.  22.5 34. ]
[0.18181818 0.30769231 0.4        0.47058824]


In [8]:
#question2


In [50]:
import numpy as np
x=np.array([[1,2],[3,4]])
#squareroot

print(np.sqrt(x))
#maximumfor axis=0
print(np.max(x, axis = 0))
#maximum for axis=1
print(np.max(x, axis = 1))
#minimum
#minimum for axis=0
print(np.min(x, axis = 0))
#minimum for axis=1
print(np.min(x, axis = 1))
#median
print(np.median(x))
#mean
print(np.mean(x))
#exp
print(np.exp(x))
#std
print(np.std(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]
[3 4]
[2 4]
[1 2]
[1 3]
2.5
2.5
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
1.118033988749895


array([2, 4])